### ISSUE TITLE
Ops built-in test failures shouldn't have return statements for void methods

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-ops#119]
When adding a test for the `Chunker` op before writing its built-ins, the test failure message included the standard variable assignment + return statement.

However, this is incorrect because the `Chunker` op does not return anything.

**Comment by hinerm** [comment]
in the case of `FFTSize` the tests are expecting a `List` return value... can't figure out why..

**Comment by bnorthan** [comment]
Hi Mark.  What was the problem with FFTSize??  Was there anything I should of done different when setting up the op?

**Comment by hinerm** [comment]
@awalter17 The `return void` problem with the `Chunker` op was a legitimate bug. It's fixed now! Thanks @ctrueden!

The `FFTSize` actually is correct in returning a list, but we had to look in the `AbstractFFTSize` method to figure this out - it has [two ItemIO.BOTH](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/fft/size/AbstractFFTSize.java#L48-52) parameters, so it effectively has two return values. The framework was just automatically converting these into a `List`

**Comment by hinerm** [comment]
@bnorthan No problem!! I was just alone without @ctrueden and didn't know why his test messages were saying a `List` was needed.

**Comment by hinerm** [comment]
But it's now clear :)

**Comment by ctrueden** [comment]
To clarify a little: this issue has nothing to do with the actual ops here. It is about the _test infrastructure_ we are creating to ensure that there are type-safe method signatures for all ops present in the core library. So the "bug" here has nothing to do with `FFTSize` nor `Chunker` per se, but rather with how the type-safe method generator I wrote was handling them. Which is to say: it generated bogus method signatures for them. :wink:
