### ISSUE TITLE
Validate op test coverage

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-ops#121]
For each Op name:

* Find corresponding Namespace test
* Ensure there is a test method for that op name

**Comment by hinerm** [comment]
@ctrueden and I can help discuss implementation details here. This is the next step after all built-ins have been added.

**Comment by ctrueden** [comment]
I think this issue is resolved, thanks to the improvements of 859a1c74f54c7527db3af5ebc3bad4f2e2853061.
