### ISSUE TITLE
Smarter OpService

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#128]
Hi @ctrueden & @hinerm 

I ran into an interesting problem, while I was playing with native `Map` operations. A native `Map` would map from a Java array A of type AT to another Java array B  of type BT, applying a function which maps AT to BT. Simple example: `IntArrayToByteArrayMap` uses a function from `int` to `byte` to map values from `int[]` to `byte[]`. Of course I these `Function`s aren't really functions, more `Computer`s with signature `O compute(I input)`, as we can't provide a native type from outside. But that's not my problem at the moment. My problem is more related to the call of the `Map`.

I want (for example) to execute the following code: 
```
	@Test
	public void testMapNativeType() {
		final Img<ByteType> in = ArrayImgs.bytes(50, 30, 50);
		final Img<ByteType> out = ArrayImgs.bytes(50, 30, 50);

                // IMPORTANT ... HERE ...
		ops.run(Map.class, out, in, ops.op(MySuperFunc.class, out.firstElement(), in.firstElement());

	}
```
Additionally, I have a `Converter` from `ArrayImg` to `byte[]`. Anyway, the problems is in the `ops.run(...)`.  The `OpService` recognizes, that there is a high priority `Map` Op mapping from `byte[]` to `byte[]`. However, my call implies, that there also exists a `MySuperFunc` which maps from `Byte` to `Byte`. If there doesn't exist such a `Function` the run will fail, even if it would work out with a different combination of `Function`s. I'm thinking of passing an `OpInfo(MySuperFunc.class, out.firstElement(), in.firstElement())`to the `OpService` and then the `OpService` can test some combinations in a smart way?

**Comment by hinerm** [comment]
@dietzc so is the problem that the `OpService` returns a `Map` op that is incompatible with the provided `MySuperFunc`? Because the `Converters` imply a substitution that violates the `MySuperFunc` contract..? (although if that's the case why can't `MySuperFunc` also use the `Converter`...?)

Also is this something that could be solved with [reducers](https://github.com/imagej/imagej-ops/issues/57)?

**Comment by dietzc** [comment]
@hinerm more or less thats the problem, yes. As I wrote, there is a very fast `byte[]` to `byte[]` `Map` op, which is matched thanks to the converters from `ArrayImg` to `ArrayImg`. However, if the `OpService` is asked for a `ByteType` to `ByteType` function (`MySuperFunc`), he will return a `ByteType` to `ByteType` op (given that there exists no operation from `Byte` to `Byte`). So the `ops.run(...)` doesn't work, which is correct. But we can be smarter, if we let the `OpService` itself figure out what is going on and just pass a  `OpInfo` object containing all the information required to match `MySuperFunc`. Having that in place, the `OpService` can detect the combination of two or more ops with the highest priority (or any other heuristic, which can be a `SciJavaPlugin` again).

**Comment by dietzc** [comment]
and while thinking about it: yes, @hinerm, you are right, this might be another use-case for the https://github.com/imagej/imagej-ops/issues/57. But we should double-check when there is a prototype.

**Comment by dietzc** [comment]
see #57
