### ISSUE TITLE
Consider simplifying Quantile and Median type hierarchies

### ISSUE THREAD

**Issue by awalter17** [imagej/imagej-ops#135]
No ops currently have the name "quantile". MedianRealType extends Quantile interface, but is named "median". Will there ever be a concrete op named "quantile"?

**Comment by dietzc** [comment]
Median is the 50% quantile. We could and will add a more generic quantile ops in the future (30%, 70% etc).

**Comment by ctrueden** [comment]
@dietzc So, you'd propose to have a general-purpose "quantile" op that takes the percentage as an argument. Then we should keep the `Ops.Quantile` toplevel interface.

But there is some confusion: we have `Ops.Median` but also `net.imagej.ops.statistics.Median', which extends it. We also have `Ops.Quantile` but also `net.imagej.ops.statistics.Quantile` which extends it. Furthermore, `net.imagej.ops.statistics.Median` extends `net.imagej.ops.statistics.Quantile`, too.

Do you like having these two different interfaces with the same name? `Ops.Foo` for the toplevel autogenerated interface for global namespaces ops with that name... and then another `Foo` in the proper package for more specific typing as needed? I think it makes sense, but is also confusing to newcomers. And `Median` extending `Quantile` makes things even more confusing at first.

Thoughts?

**Comment by dietzc** [comment]
A lot of this will be also addressed in our work on https://github.com/imagej/imagej-ops/tree/outputop-service. I will try to file clean, atomar PRs for the feature sets theses days such that you see what I mean. Maybe some problems can be solved with this PR.

**Comment by ctrueden** [comment]
Note that there is now a `stats.quantile`, implemented in `DefaultQuantile`. I don't see a `MedianRealType` class anymore. I think this issue can be closed (although there are other problems with the median/quantile/percentile ops... the type hierarchy is no longer one of them—they all just extend `AbstractStatsOp` now).
