### ISSUE TITLE
Hyperslice 2D Interval and 3D Image

### ISSUE THREAD

**Issue by DanielSeebacher** [imagej/imagej-ops#137]
I don't know if this is a bug or if I'm just using the Hyperslice wrong, but an error is thrown when I want to use the Hyperslice Op with a 2D Labeling and a 3D Image. I have included a simple test to illustrate the problem. 

https://github.com/imagej/imagej-ops/blob/hyperslice-test/src/test/java/net/imagej/ops/slice/HypersliceTest.java#L133-149

**Comment by DanielSeebacher** [comment]
fixed in dc23906f9a204ef9d31a148109756ad86e1a486e.

**Comment by hinerm** [comment]
@DanielSeebacher it's good to wait to close the issue until the PR is merged. The issue will be closed automatically if [certain keywords are used](https://help.github.com/articles/closing-issues-via-commit-messages/).
Anyway, if a branch is not rebased against the latest master, the commit parents will change and thus the hashes of the commits in the PR will change.
So in this case, the commit on master that fixed this is https://github.com/imagej/imagej-ops/commit/20873cadf61fb0905bc2e86860a1604436c51b9d

**Comment by hinerm** [comment]
P.S. thanks for the fix :octopus:
