### ISSUE TITLE
Enforcing usage of certain ops

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#154]
Hi all,

@StephanPreibisch and I discussed, that in some situations, one really wants to make sure that a certain `Op` is chosen, even if there exists another `Op` with the same parameters with the same priority. That's already possible of course, by requesting exactly this `Op` at the `OpService`. However, that is not always possible, for example see https://github.com/imagej/imagej-ops/blob/dog/src/main/java/net/imagej/ops/dog/DefaultDifferenceOfGaussian.java. This `Op` executes `gauss(...)` on the `OpService` which then selects the `Gauss` with the highest priority. Again, sometimes one has to exactly specify the `Op` used by (in this case) `DoG` (e.g. selection in an UI which `Op` should be used... CUDA vs. CPU vs. ...).  It would be possible that the `DoG` takes a `Class<? extends Gauss.class>` as optional input and therfore allows the programmer to specify the used method, but maybe we can figure out a more general mechanism to enforce certain ops, e.g. by passing them in the `run` or `op` call? Potentially, this is also related to https://github.com/imagej/imagej-ops/pull/143. 

Cheers,

Christian

**Comment by ctrueden** [comment]
This requires careful thought. Can we discuss at the next hackathon? Or do you need a solution sooner?

**Comment by dietzc** [comment]
sure! Hackathon! Hackathon! Hackathon! Hackathon! Hackathon! Hackathon! Hackathon! Hackathon!  :-)

**Comment by ctrueden** [comment]
My current thinking on this issue is the use of "hint" flags as inputs to ops, which then delegate accordingly. Ideally, the best op should be selected automatically whenever possible, but of course this is not always practical. So hint flags are a nice solution because they formalize the selection within the ops framework itself—i.e., they are part of the input parameters.

**Comment by dietzc** [comment]
So you mean Hints as optional input?

**Comment by ctrueden** [comment]
> So you mean Hints as optional input?

Right. We can discuss and scheme further during the hackathon.

**Comment by ctrueden** [comment]
I think we solved this in #202. Now, you can override the `OpEnvironment` to behave however you want. Also, our pattern is now to have "low-level" ops that take other `Op`s as input (typically `ComputerOp`s and/or `FunctionOp`s), so you can override the behavior on a very granular level.

So I'm closing this as fixed. Please reopen if you still see chinks in the armor.
