### ISSUE TITLE
Come up with concise documentation about the naming strategies

### ISSUE THREAD

**Issue by dscho** [imagej/imagej-ops#16]
We had a couple of renamings recently, and it would probably be a good idea to document a unified idea of how to name things. Which means that we first have to unify our ideas to name things ;-)

**Comment by ctrueden** [comment]
I started a document [on the wiki](https://github.com/imagej/imagej-ops/wiki/Naming). It is not fully specified, but it's a start. We will continue to update and flesh it out as needed.
