### ISSUE TITLE
Add Math-Operations for IterableIntervals/RandomAccessibleIntervals/ArrayImgs

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#161]
At the moment there exist no implementations to subtract, divide, multiply or add two `IterableInterval`s and/or `RandomAccessibleInterval`s.

Following cases: 
* The most general case would be a `BinaryMap` which takes a `BinaryFunction`: 

** `RandomAccessibleInterval` = `RandomAccessibleInterval` operator `RandomAccessibleInterval` based on `Views.flatIterable`. 

** `IterbaleInterval` = `IterableInterval` operator `IterableInterval` with conforms on `IterationOrder`.
* Fast implementations for `ArrayImg`s, directly operating on the arrays (we have the pay attention for the "unsigned" types and potentially add parallelization.

Does this make sense? Did I forget something?

**Comment by ctrueden** [comment]
The idea here was to expand all the add ops in `net.imagej.ops.math.add` to include sub, mul and div as well, and maybe other things too if easy. Probably autogenerated. This would be a good student project.

**Comment by dietzc** [comment]
So parts of `net.imagej.ops.math.add` will also be auto-generated? Makes sense.

**Comment by LeonYang5114** [comment]
See https://github.com/imagej/imagej-ops/pull/219
