### ISSUE TITLE
LazyOps

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#173]
Hi all,

while refactoring the `Normalize` ops a bit, I figured that the concept of `LazyOp`s now nearly fits into our op-design. The latest refactoring of @ctrueden made it possible that we can nicely implement `FunctionOp`s which do not create a new output, rather return a converted or transformed view on the input which is lazily evaluated.

However, nearly always (at least I can't think of a case where it doesn't work) the result of a lazy op can be copied into a container (mostly an `Img`) and therefore we can always offer a non-lazy version of a `LazyOp` or we can provide non-lazy versions of a `LazyOp` which are optimized and therefore faster than `LazyOp` +  `Copy`. Anyway, we want to provide the user the ability to chose what she wants. 

Here is the problem: From an API point of view  (`ops.namespace().something(...)`), the calls are exactly the same. We could add a `boolean doLazy` flag to the method signatures manually, but this doesn't fit with our `NamespaceTest`s. Additionally, we potentially may want to test if the `LazyOp` produces exactly the same result as the non-lazy version and also we may want to auto-generate (code-generation, or op-reducer) the non-lazy version of a `LazyOp` (if there is no faster special implementation available).

So here is my question: Can we somehow in integrate the concept of `LazyOp`s in our current ops-design?

Thanks,

Christian 

PS: Some examples: `Converter`: https://github.com/imagej/imagej-ops/pull/174 `View`: https://github.com/imagej/imagej-ops/pull/168
PPS: potentially this is all related to https://github.com/imagej/imagej-ops/issues/57

**Comment by ctrueden** [comment]
There are three relevant patterns here:

1. __Explicit.__ Do work on input object `in`, saving the result to output object `out`. Pay time cost once, up front. Pay space cost once, up front.
2. __Lazy.__ Return an output object `out` that is a thin wrapper around input `in`. When API methods are called on `out`, work is done on demand. Pay time cost only on demand but potentially multiple times. Pay space cost on demand, potentially multiple times.
3. __Lazy + cached.__ As Lazy, but caching the result after it is computed once. This is the "lazy" approach taken in various other places in SJC, although the space costs for doing it are much more trivial than they are for images etc.

My preference for ops, in all cases, is to differentiate ops by: A) op name and B) input types. The `boolean isLazy` parameter does that, although it does not differentiate between patterns 2 and 3 above. It may be better to use a "hints" object for specifying this.

We could certainly add abstract type layer(s) that facilitate patterns 2 and 3 above as generally as possible, although with all the caching code in the works, I'm reluctant to throw yet another thing into the mix until we've had time for things to settle a little. My intuition is one of the other caching-related efforts will help a lot with this problem—we can code things to either pattern 1 or 2 above, and then get pattern 3 "for free" from the cache somehow.

I do see the value in some sort of `Future`-esque thing for generalizing the lazy evaluation. This would facilitate smarter caching in cases where it makes sense. And avoid the need to explicitly code lazily-evaluated ops, _ever_. That is: you'd only code pattern 1 above, and the framework would take care of providing you something like a `Future` object back for asynchronous evaluation.

**Comment by ctrueden** [comment]
Anyway, this is a good topic for discussion at the hackathon. We want to avoid proliferating a bunch of signatures for lazy vs. non-lazy evaluation. Best would be to only code the explicit ops always, and then have a mechanism in the framework for doing the lazy version. This might be output-type-specific, though... needs more discussion and thought.

**Comment by ctrueden** [comment]
I guess there are cases where you want to code only a lazy object, too. `Views` is the big one, but others are similarly possible. So the goal is to have framework support for each, to avoid ever needing to code both for a specific op.

**Comment by dietzc** [comment]
`View's and `Converter`s often or always(?) have a corresponding non-lazy version. Copying the result into another container is often a solution. Of course this doesn't hold for `RealView`s. There you have to specify a certain `Interval` to make it persistent.

**Comment by dietzc** [comment]
Actually, besides `View`s, nearly any `Map` operation could be evaluated lazy. Might not always make sense, but in theory we could.

**Comment by ctrueden** [comment]
I am still waffling on this a lot internally. Definitely looking forward to discussing in person at the hackathon. I think trying to hash it out in the PR here would be a lot more painful.

**Comment by ctrueden** [comment]
We indeed discussed quite a bit at the hackathon. More details coming later.

**Comment by LeeKamentsky** [comment]
I'm looking forward to seeing the outcome of this - it will be interesting. One thing I like about OPs is that you make a machine for doing something and then you put it in motion. So, what you're missing is something that can look at the machine and run it in the way that makes sense. Or maybe there is more than one machine or you could use this gizmo or that one to do the job. So, a graph with one path that's cacheing and another that's not or one path that uses one memory layout or another, one that uses GPUs and another that uses CPUs and a shortest-path algorithm that finds you the machine that you should run. IMHO, the thing that's missing is a way for an OP to report its estimate of the cost of running X in terms of memory, cycles, cache misses, etc - think of how you'd model what happens inside that thing on your lap that's running FIJI or Knime.
In some ways, it reminds me of how they do quantum physics. The thing that you end up observing could have happened this way or that and the probability that you see it is calculated over all paths and, under one interpretation, the machine is only run when you need to look at it. So maybe that's when you run the optimizer and stop building your machine - when you look at the output.

**Comment by ctrueden** [comment]
So, it seems we never wrote up what we discussed in January. Here's my recollection:

* We put the suffix `View` after any op that does its work on demand. So e.g. `transform.rotateView` means "give me back an object that is a rotated _view_ of the original." So in all ways it behaves the like an actual rotation, but you didn't need to copy pixels, resample, etc.

* More generally, `transform.rotate` means "give me back a rotated version—and I don't care if it's a view or you actually change pixels." So if you want to code a destructive rotation, you would label it `transform.rotate`.

* All `transform.rotateView` ops are also `transform.rotate` ops—the `View` suffix is a further specialization.

* The special `transform.burnIn` op (or whatever we decide to call it) is sort of like the identity operation—except that it makes a copy if the object being burned in is currently a view. We added a `View` marker interface to ImgLib2 so that you can always ask any object whether it is a view. The `burnIn` op will call `copy` on the object if it's a view, and return the input instance of it's not known to be a view. In this way, you can ensure you have an object that won't pollute other objects if/when it gets mutated.
