### ISSUE TITLE
ThresholdNamespace: Don't restrict to Img

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#177]
Hi all,

while using the `ThresholdNamespace` I figured that some of the methods (e.g. https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/threshold/ThresholdNamespace.java#L794) are restricted to `Img` objects which is really to specific, as threshold `Op`s can operate on `IterableInterval`s.

It would be great, if we could change that, because then all threshold methods can be applied to arbitrary subsets of any kind of `RandomAccessibleInterval`s (e.g. plane-wise processing or processing on `LabelRegion`s derived from `ImgLabeling`s).

Thanks,

Christian

**Comment by ctrueden** [comment]
Looking at [the code](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.16.0/src/main/java/net/imagej/ops/threshold/AbstractApplyThresholdImg.java#L56-L65
), they all take `Img` so they can be hybrid ops which know how to produce the `BitType` output `Img`.

Note that `AbstractApplyThresholdImg` does extend `AbstractApplyThresholdIterable`. I guess you could make two separate class hierarchies: one for `Img` which is a `HybridOp` and one for `Iterable` which is a pure `ComputerOp`.

**Comment by dietzc** [comment]
> Looking at the code, they all take Img so they can be hybrid ops which know how to produce the BitType output Img. 

It would be enough if they would be `IterableInterval`. See: https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/create/img/DefaultCreateImg.java.

I would _always_ vote against using `Img` because in most of the cases, especially with the new `CreateOp`s there is from my point of view really not benefit using `Img` in favour of `RandomAccessibleInterval` or `IterableInterval`. The `Op's we create should be able to run on arbitrary subsections (`Views`) on the `RandomAccessibleInterval` and therefore we can't restrict it to `Img`. I'm happy to change this and open a PR if you agree.

**Comment by ctrueden** [comment]
@dietzc I don't get it; `DefaultCreateImg` also works only with `Img`, not `IterableInterval`. How do you deal with the issue of `ImgFactory` otherwise, since `IterableInterval` doesn't know how to clone itself?

**Comment by ctrueden** [comment]
Anyway, I agree we should change it to work with objects that come out of `Views`—I'm just trying to understand how you can achieve that when use of `ImgFactory` and/or `HybridOp` is involved.

**Comment by dietzc** [comment]
We actually implement the `DefaultCreateImg` https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/create/img/DefaultCreateImg.java that it can handle `IterableInterval<>`s based on heuristics (which are replaceable):

* If it's an `Img` use the underlying factory with the passed or guessed type
* If it's not an `Img` and no `ImgFactory` is passed, use the following heuristic: `Size > Integer.MAX` go for `CellImg`, `ArrayImg` else (there is no reason for any other container in the general case).
* If no type is provided, use the default type, which is `DoubleType`. 

In the case of `HybridOp`s, the heuristic described above will be used if e.g. there is no `Img` passed and input. But especially `HybridOp`s can always accept the output as well and therefore the user can decide if he wants the output to be something special (e.g. `NtreeImg` or `PlanarImg`).

**Comment by ctrueden** [comment]
Aha, I should have read the code more carefully. I just glanced at the parameters and saw `Img<T>` and stupidly missed that that is the _output_. But the input template (if any) is `dims`! That is potentially very surprising/misleading.

I'm not sure we want to use `DefaultCreateImg` as the template after which to model all our logic—the current implementation has serious generics-related issues (#160). I'll comment on that issue with details on a proposed fix (since it is tangential to this issue here).

**Comment by dietzc** [comment]
> I'm not sure we want to use DefaultCreateImg as the template after which to model all our logic—the current implementation has serious generics-related issues (#160). I'll comment on that issue with details on a proposed fix (since it is tangential to this issue here).

I agree and thanks for your suggestions concerning the refactoring of `DefaultCreateImg`, we will give it a try.  It makes sense.

Anyway, there are many  `HybridOp`s or `FunctionOp`s which have to create an output and we probably don't want to have thousand versions of them with parameters for each and every potential output type. Additionally, I'm convinced that using `Img` in any signature of a method in a namespace as an input or output just limits us in what we can do with the `Op`. The best an `Op` can do is asking: "I have this input+parameters, give me a suitable output which is a e.g. `RandomAccessibleInterval`". The "magic suitable" part we have to solve with heuristics (number of pixels for example for the container) if the parameters don't provide the information.

**Comment by stelfrich** [comment]
> while using the ThresholdNamespace I figured that some of the methods are restricted to Img

As far as I can tell, the original concern has been addressed by @kephale in 37f54e18.

`DefaultCreateImg` has also been remodeled as per suggestion which also includes the special ops concerns.

@dietzc Could you check your last comment and see if it has been addressed? If yes, we can close this..

**Comment by dietzc** [comment]
thx!
