### ISSUE TITLE
CustomOpEnvironment: Split into two versions with different behaviour

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#200]
For the scenario in which you may want to pass additional `CommandInfo`s to a parent `OpEnviroment` one may want to chose between two options:

* Merge the existing `OpIndex` with the added `CommandInfo`s. 
* Try to match `Op`s first given the added `CommandInfo`s and just fall-back to the existing `OpIndex` if we couldn't match an `Op` in the first try.

Naming suggestions: `JointCustomOpEnviroment` and `PrioritizedCustomOpEnvironment`.

**Comment by ctrueden** [comment]
`CustomOpEnvironment` is actually both, because it sets the additional ops to `FIRST_PRIORITY`.
