### ISSUE TITLE
NullPointerException in conforms()

### ISSUE THREAD

**Issue by seebacherd** [imagej/imagej-ops#208]
When calling Ops using the ops().geometric().area(...) way a NullPointerException is thrown in the conforms method when in() is called.

**Comment by dietzc** [comment]
Branch? Failing test to reproduce?

**Comment by seebacherd** [comment]
geometric branch and half of the tests in ```GeometricTest```

**Comment by dietzc** [comment]
`testArea`actually passes.

**Comment by dietzc** [comment]
and the other tests fail because (for example) this: `function = ops().function(MinorMajorAxis.class, Pair.class, Polygon.class);` You should pass `in()` here rather than `Polygon.class` (and maybe rename the field function to `minorMajorAxisFunc`.
