### ISSUE TITLE
Relax requirements of op(...) calls on OpEnvironment

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#214]
@ctrueden:
> So, as I also mentioned in the Gitter channel: we may need to relax the return value of op(Class, ...) to return simply Op. And make sure there is a common method of the environment you can override that will affect all calls including op, function, hybrid, etc.

in https://github.com/imagej/imagej-ops/pull/205.

**Comment by ctrueden** [comment]
I addressed this need in 186db859406d3d5451aeded3ef3e17b9bfd0af8c, which adds a new `OpEnvironment#op` signature that accepts an `OpRef<?>` and returns `Op` (not an `OP extends Op` generic). From the javadoc of that new method:
```java
 * NB: While it is typically the case that the returned {@link Op} instance is
 * of the requested type(s), it may differ in certain circumstances. For
 * example, the {@link CachedOpEnvironment} wraps the matching {@link Op}
 * instance in some cases so that the values it computes can be cached for
 * performance reasons.
```
This method is the central lookup method used by all `Computers`, `Functions`, `Hybrids` and `Inplaces` utility lookups. This makes it easy for custom op environments such as the `CachedOpEnvironment` to customize op lookup behavior as needed.
