### ISSUE TITLE
Velocity Templates: Map and List

### ISSUE THREAD

**Issue by Squareys** [imagej/imagej-ops#23]
Hello @ctrueden @dscho, 

I had a look at velocity templates which support amazing features e.g. foreach, maps and arraylists. 
Since the groovy script parses all variable values from the .list as Strings, I didn't find a way to access theses features, though. 

A line like this `list = [1, 2, 3]` would be set in the velocity context as literally `"[1, 2, 3]"` and therefore can't be iterated via foreach.

I modified the groovy script to parse Maps and Lists and Maps in Lists manually.
See https://github.com/Squareys/imagej-ops/tree/velocity-types
Left to do is maybe parsing numerical values? I tried to find a way to let velocity do the parsing, I hope I didn't miss anything.

Also, there is a nifty `$foreach.hasNext` feature, which is only available with velocity 1.7 and upward, maybe we could use that instead? 

Greetings,
Jonathan (Squareys)

**Comment by ctrueden** [comment]
For anyone who stumbles upon this issue in the future, note that the list parsing was changed to simply use Groovy—which works awesomely. b5d3778ea64542e0095090ca0b477094c4fbbfc6
