### ISSUE TITLE
Handle optional parameters of same type in (Threshold)Namespace methods

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-ops#233]
I am taking the `ThresholdNamespace` as example here, although the issue might also apply to other namespaces. The following method declaration is complete with two parameters `r` and `k` and calls a specific `Op.run()` with all parameters:

```
public <T extends RealType<T>> BitType localSauvola(final BitType out, final Pair<T, Iterable<T>> in, final double r, final double k)
```

If both the `r` and `k` parameters of the called `Op` are, however, optional, the two resulting methods in the namespace share the same signature `localSauvola(BitType, Pair<T, Iterable<T>>, double)`. Currently, there is no sensible way to handle that clash and be able to distinguish which parameter is provided.

See also https://github.com/imagej/imagej-ops/pull/226 and https://github.com/imagej/imagej-ops/pull/225.

cc @ctrueden @dietzc

**Comment by ctrueden** [comment]
To clarify: when multiple optional parameters exist for an op, there should not be every possible combination of method signatures. Rather, optional parameters are "dropped" from right to left.

So in this case, you would want signatures:

```java
<T extends RealType<T>> BitType localSauvola(BitType out, Pair<T, Iterable<T>> in, double r, double k);
<T extends RealType<T>> BitType localSauvola(BitType out, Pair<T, Iterable<T>> in, double r);
<T extends RealType<T>> BitType localSauvola(BitType out, Pair<T, Iterable<T>> in);
```

Does that address your concern? Or am I misunderstanding the problem?

**Comment by dietzc** [comment]
@ctrueden makes sense. I can't think of another solution, too. Maybe that you provide different method signatures, but then we would only complicate things.

@stelfrich if you adapt your branches accordingly, I will review and merge!

**Comment by ctrueden** [comment]
To be completely clear: what I describe above is the status quo right now. Ops works like this now, and no code changes will be required. There are many examples of ops with several optional parameters that have multiple method signatures, with varying number of args. The completeness checks (part of the unit tests) verify that all of these are present. I do not think it is worth it (nor feasible in cases like the one described above) to add additional overloaded method signatures for "non-canonical" combinations of parameters.

**Comment by ctrueden** [comment]
A couple of other notes:

* Some day we will be able to use the [`@Nullable` annotation](http://stackoverflow.com/q/14076296/1207769) (or similar), which can mark optional parameters in built-in methods. But the proposal to include this into core Java was not accepted yet, unfortunately.

* Regarding built-in method signature clashes, there is a related phenomenon that _can_ result in a clash: two ops with the same type arguments. When that happens, you have to write `@OpMethod(ops = {...})` to indicate all op implementations that share that built-in method signature. And in the method body, make an `ops.run(...)` invocation that could potentially match either. And ideally name the parameters of both ops congruently, too, to avoid confusion.
