### ISSUE TITLE
Create BinaryOp for Math (or other interfaces if applicable)

### ISSUE THREAD

**Issue by LeonYang5114** [imagej/imagej-ops#273]
Right now we only have add/div/mul/sub Ops between Images. More operations should be included such as min/max/avg/and/or/etc. This could be done by adding more templates; <del>or (use Map) creating some ComputerOp that takes a RandomAccess or RAI as parameter, a long[] as input, and writes the value of that RA at that position to the output;</del>or any other ideas?

**Comment by LeonYang5114** [comment]
After talking with @ctrueden we thought that creating BinaryOp could solve this problem (without caring for the lossiness right now). @dietzc Do you think we have other workarounds for this?

**Comment by dietzc** [comment]
> This could be done by adding more templates; or (use Map) creating some ComputerOp that takes a RandomAccess or RAI as parameter, a long[] as input, and writes the value of that RA at that position to the output; or any other ideas?

I don't understand this part. If you want to implement e.g. a `max` between two images, why do you need a `long[]`?

**Comment by dietzc** [comment]
Maybe I understand: You want to make sure that two `RandomAccessibleInterval`s are mapped correctly, no matter what `IterationOrder` they have? But again, then you don't need a `long[]`.  Assuming they don't have same iteration order (test on the output of `Views.iterable(...)`): You iterate over the first `RandomAccessibleInterval` using `Views.iterable(...)`. You set the position of the second one (the RA of it) on the position of the `Cursor`. You compare both of them and write it into the output. First one would be the input parameter of the `FunctionOp` or `ComputeOp`, second one a `Parameter` of the op.

**Comment by ctrueden** [comment]
Suppose you want a binary function `add(imgA, imgB)` which returns `imgC`. This is a pure function.

We have `add(a, b)` which return `c`, where `a`, `b` and `c` are `T extends RealType<T>`: it is implemented in `RealBinaryMath.Add`.

The goal is to write a `map` expression to achieve the `add(imgA, imgB)` to a new output image, which matches the `RealBinaryMath.Add` and then repeatedly reuses it across the `imgA` and `imgB` elements (presuming same dimensionality, image size and iteration orders of course).

Can this be done using the framework as is? I'm looking at `MapIterableIntervalToIterableInterval` and `MapRAIToIterableInterval` and `MapIterableIntervalToRAI`. But those are for _unary_ `ComputerOp`s. The signatures are:

```java
	(RandomAccessibleInterval out) =
	net.imagej.ops.map.MapIterableIntervalToRAI(
		RandomAccessibleInterval out,
		IterableInterval in,
		ComputerOp op)
	(IterableInterval out) =
	net.imagej.ops.map.MapRAIToIterableInterval(
		IterableInterval out,
		RandomAccessibleInterval in,
		ComputerOp op)
	(Iterable out) =
	net.imagej.ops.map.MapIterableToIterable(
		Iterable out,
		Iterable in,
		ComputerOp op)
```

The above three `map` ops are all `ComputerOp` which means the output must be specified. As such, we try to achieve the end goal:

```java
imgC = ops.create().img(imgA);
ops.map(imgC, imgA, imgB, ops.op(c, a, b));
```
But there is no such _binary_ map operation!

We would need one that takes an `Iterable<A>`, an `Iterable<B>` and a `BinaryOp<C, A, B>`, and which produces an `Iterable<C>`.

Apologies if I am being stupid and missing something obvious here.

**Comment by dietzc** [comment]
Yep, I understand the use-case of a `BinaryOp`, however I still don't understand what the `long[]` should do? 

~~Anyway, as you know, I like the idea of having `BinaryOp`s. However, I remember we had a discussion about this and at this point in time we decided against `BinaryOp`s as we could use `Pair<I1,I2>` as input or go on with the pattern we currently use (`I1` is the  `FunctionOp` or `ComputerOp` input parameter, while `I2` is an additional parameter of the plugin, which can't be set in the `compute`).  Both patterns I don't really like. ~~

.... And now while writing this I understand everything and completely agree. We need `BinaryOp` and it makes sense. We also need to convert all existing ops then, which use one of the two aforementioned workarounds. 

> (presuming same dimensionality, image size and iteration orders of course)

We can solve this issue using clever `Converter` hierarchies.

**Comment by LeonYang5114** [comment]
@dietzc Sorry about the long[] stuff, which I come up with on my own and I understand that it would be quite "dirty" an approach (I was trying to use a long[] to indicate the pixel location of the parameter image). If we are going to have binary ops, then long[] would be definitely not necessary. 

Another thing is that, do we want to embed some existing unary ops (such as add/sub/div/mul) into the binary ops we create, or keep them so we have both in different classes? As far as I can see, the binary version of Add has the complete functionality of the unary version, and works as intuitively (as least to me). Also  the binary op would not be more computationally expensive.

**Comment by dietzc** [comment]
> @dietzc Sorry about the long[] stuff, which I come up with on my own and I understand that it would be quite "dirty" an approach (I was trying to use a long[] to indicate the pixel location of the parameter image). If we are going to have binary ops, then long[] would be definitely not necessary. 

Ok now I understand! Please checkout the `Localizable` interfaces. For example a `Cursor` implements this one, so you don't have to go the `long[]` way.

> Another thing is that, do we want to embed some existing unary ops (such as add/sub/div/mul) into the binary ops we create, or keep them so we have both in different classes? As far as I can see, the binary version of Add has the complete functionality of the unary version, and works as intuitively (as least to me). Also the binary op would not be more computationally expensive.

@ctrueden should comment on this. But a quick preview: Maybe we can have one `Op` which is both (see gitter). However, if this is not possible I vote for only `BinaryOp`, this means converting all existing old `Op`s.

**Comment by LeonYang5114** [comment]
Probably not all the ops. I thin some are inherently unary, like not, sqr, sqrt, or copy, right?

**Comment by tpietzsch** [comment]
Hi guys,
I still don’t get it... Why is the Pair<I1,I2> not a feasible solution?
best regards,
Tobias

**Comment by ctrueden** [comment]
@tpietzsch Imagine I want to obtain a binary `ComputerOp` which operates on two `T` instances, producing another (preallocated) `T` as output, where `T extends RealType<T>`.

My Java method signature is:

```java
<T extends RealType<T>> T add(T out, T a, T b)
```

But I cannot type-safely specify a need for this with the current `computer` methods of the `OpEnvironment`. I can only write:

```java
ComputerOp<T, T> addComputer = ops.computer(Ops.Math.Add.class, out, a, b);
```

But I really want it to be _binary_ type-safe on both inputs _and_ the output, right?

So we use `Pair<T, T>` as you suggest, changing our op to:

```java
<T extends RealType<T>> T add(T out, Pair<T, T> in)
```

Already, this is confusing to those using the library, since they now have to create this `Pair` thing in order to use it at all. Of course, we could require that all `Pair` usage is also expanded into a convenience method with the pair split in half, and/or use the "op reducer" mechanic we are considering implementing, but these things also add complexity, and cost time to implement.

Setting aside that possible confusion, how does our call to `computer` look now?

```java
ComputerOp<T, Pair<T, T>> ops.computer(Ops.Math.Add.class, out, new Pair<T, T>(a, b));
```

Which, in actual practice, will ___not___ limit the type matching to `Pair<T, T>`, but only to `Pair` in general. It can be accomplished by implementing `Contingent` with a `conforms` implementation that verifies that the two constituent `Pair` elements are in fact `RealType`—or even the same kind of `RealType`—but not necessarily `T extends RealType<T>` since the `T` is a generic erased at runtime.

Much more elegant and simple, IMHO, is:

```java
BinaryComputerOp<T, T, T> ops.binaryComputer(Ops.Math.Add.class, out, a, b);
```

Where the actual `Add` op implementation in question in fact implements `BinaryComputerOp` with proper method accessors and generic typing, for both type safety and runtime convenience.

**Comment by LeonYang5114** [comment]
see https://github.com/imagej/imagej-ops/tree/binary-ops

**Comment by LeonYang5114** [comment]
see branch [refactor-math](https://github.com/imagej/imagej-ops/tree/refactor-math)

**Comment by ctrueden** [comment]
So, we have binary ops now. Great!

So @LeonYang5114, what else do you want to do for this issue?

**Comment by LeonYang5114** [comment]
I am just waiting for someone to close it. It seems that I should do it haha.
