### ISSUE TITLE
Smaller size test image for GeomTest

### ISSUE THREAD

**Issue by LeonYang5114** [imagej/imagej-ops#293]
Right now the [GeomTest](https://github.com/imagej/imagej-ops/blob/master/src/test/java/net/imagej/ops/geom/GeomTest.java) takes about 4 seconds to run in my laptop, which is relatively much slower than other unit tests. Idealy it should not take more than 1 or 2 seconds. 

This [test image](https://github.com/imagej/imagej-ops/blob/master/src/test/resources/net/imagej/ops/geom/cZgkFsK.png) might be too large for a quick test. We could use a smaller image, and do testing on the larger one only when "imagej.ops.expensive.tests" is set to true. The expected values need to be changed accordingly.

**Comment by LeonYang5114** [comment]
I created this branch https://github.com/imagej/imagej-ops/tree/optimize-geom-test but it seems that a smaller size image (1/25 by area) does not help reduce the running time of the test. Actually, even if I make one of the test (testBoundarySize2D) empty, that test still takes 0.6 seconds to run (that's only about 0.5 sec better than original). This is still the case after I remove the "@BeforeClass" method. I am not sure if this only happens on my laptop.

I really cannot understand this bizarre behavior. I know this is not of high priority but I am very interested in this problem. @ctrueden Any idea?

**Comment by dietzc** [comment]
maybe @seebacherd and @tibuch can comment on this?

**Comment by LeonYang5114** [comment]
The bizarre behavior I mentioned above seems to be related to JUnit, but the performance issue actually is due to the tests on the 3D test image. See https://github.com/imagej/imagej-ops/pull/294 for more detail.
