### ISSUE TITLE
Any usable op should rarely extend AbstractOp directly

### ISSUE THREAD

**Issue by LeonYang5114** [imagej/imagej-ops#309]
Unless for rare reasons, a usable (not abstract) op should not extend AbstractOp directly, since we have created the `NullaryOp` family, and those ops should at least extend e.g. `NullaryFunctionOp` or `NullaryComputerOp` or whatever `SpecialOp` as proper.

For example, the [DefaultCreateImg](https://github.com/imagej/imagej-ops/blob/76e7bba1bd541efd5f47b13f91cf379ffd9b4223/src/main/java/net/imagej/ops/create/img/DefaultCreateImg.java#L57-L58) could extend `AbstractUnaryFunctionOp<Dimension, Img<T>>` instead.

**Comment by ctrueden** [comment]
Addressed by #315.
