### ISSUE TITLE
Lacking way to obtain "hidden" ops without matching their class explicitly

### ISSUE THREAD

**Issue by LeonYang5114** [imagej/imagej-ops#320]
======== Problem Description ========
Hidden ops: ops that have conflicting signatures with other ops of higher priority. For example:
```Java
@Plugin(type = Ops.Image.Test.class, priority = HIGH_PRIORITY + 10)
public class OpA extends AbstractUnaryComputerOp<Img<Type>, Img<Type>> implements Ops.Image.Test {...}
@Plugin(type = Ops.Image.Test.class, priority = HIGH_PRIORITY)
public class OpB extends AbstractUnaryComputerOp<IterableInterval<Type>, IterableInterval<Type>> implements Ops.Image.Test {...}
```
Suppose the additional parameters of `OpA` and `OpB` are of the same types. Then `OpB` is hidden by `OpA`. The calls `Computers.unary(ops(), Ops.Image.Test.class, out, in, otherArgs)` will never return instance of `OpB`.

Right now, if we really want to use `OpB`, we would either call
- `ops().image().test((IterableInterval<Type>) out, (IterableInterval<Type>) in, otherArgs)` or
- `Computers.unary(ops(), OpB.class, out, in, otherArgs)`

(notice that `Computers.unary(ops(), Ops.Image.Test.class, out, in, otherArgs)` will cause an infinite loop since it will match `OpA` repeatedly)

It is very likely that `OpA` is an op that does some extra stuff than `OpB`, so that `OpA` will call `opBInstance.compute1(...)` in its own `compute1`. Since the first way above does not return an instance of `OpB`, we can only use the second one.

If a user creates a `OpBCustomized` with same signature as `OpB` and `priority = 5`, we would expect that any matching to `OpB` should be directed to `OpBCustomized`. However, since the second way mentioned above matches with an explicit class name, `OpA` will still use `OpB` to do the work.

======== Propose Solution ========
Have some way to tell the matcher the exclusive upper bound of priority we want. In this case, we could pass `HIGH_PRIORITY + 10` to `ops()` so that `Computers.unary(ops(), Ops.Image.Test.class, out, in, otherArgs)` will match `OpBCustomized`.

**Comment by ctrueden** [comment]
I believe that adding priority filtering to the matcher would make the design too complicated.

If an op needs a computer of the same type that it itself is, this danger of infinite recursion exists. But I think such loops can be avoided with intelligent use of interfaces. I.e.: `OpA` should request an `image.test` op of a _different_ interface than it itself is. Would that work?
