### ISSUE TITLE
Integral images

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-ops#331]
Migrate the [existing implementations of integral images](https://github.com/imglib/imglib2-algorithm/blob/master/src/main/java/net/imglib2/algorithm/integral/IntegralImg.java) from imglib2 to Ops.

**Comment by ctrueden** [comment]
@stelfrich I invited you. Please assign yourself. :wind_chime:

**Comment by stelfrich** [comment]
Closed by #376.
