### ISSUE TITLE
Use explicit class in unit tests

### ISSUE THREAD

**Issue by LeonYang5114** [imagej/imagej-ops#365]
After merging #348, calling an op method no longer guarantees the usage of some specific op. Therefore, wherever a specific op is needed, its explicit class should be used (in contrast to its interface in `Ops`). This is usually the case in the unit tests. This will also be the principle for future unit tests: if you are testing a specific op, don't use the op method that is correspond to its signature.

If no one has started on this yet, I would probably do it later.

**Comment by ctrueden** [comment]
Addressed in #388.
