### ISSUE TITLE
Namespace completeness for HybridCFs with optional parameters

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-ops#379]
`HybridCF`s with optional parameters highlight some issues with matching. An Op with the following example signature

```
(RandomAccessibleInterval out?) =
    net.imagej.ops.image.integral.DefaultIntegralImg(
        RandomAccessibleInterval out?,
        RandomAccessibleInterval in,
        int order?)
```

should have (according to my understanding) a method `method(RandomAccessibleInterval in, int order)` in the namespace. During the completeness test the [`DefaultOpMatchingService.java#L309`](https://github.com/imagej/imagej-ops/blob/43074652368c1e4335ce666f9f6331d1142a2d40/src/main/java/net/imagej/ops/DefaultOpMatchingService.java#L309) pads the arguments to `[net.imglib2.RandomAccessibleInterval, int, null]` which does not match the aforementioned candidate. An `int` cannot be assigned to an argument of type `RandomAccessibleInterval` after all.

This seems to be a general issue with `HybridCF`s with additional optional parameters, where the candidates have optionals on the left and the right of arguments.

See also #376.

**Comment by LeonYang5114** [comment]
I think the rule was that the optional parameters are filled in from left to right. Therefore, if you want to provide an "order" to the call, you need to first provide an "out".

I do agree that this is not very intuitive. @ctrueden any thought?

**Comment by stelfrich** [comment]
> I think the rule was that the optional parameters are filled in from left to right.

That's right @LeonYang5114. That rule, however, conflicts with the rule that `out` shall be the first parameter, like `op(out, in, params)`.

One solution would be to relax the second rule and switch `out` and `in` in cases of `HybridCF`s. But that doesn't seem like a desirable option to me (it would confuse me a lot..). And at that point my imagination is exhausted.

**Comment by ctrueden** [comment]
Yes, the optional parameters are always dropped from right to left. We explored other options during the Jan 2015 hackathon, and concluded it was untenable to do otherwise.

So yes, the `out` parameter is always the last to go.

> One solution would be to relax the second rule and switch `out` and `in`

As you probably know by now, my number one rule is consistency. So I strongly oppose waffling on the order of `out` vs. `in`. The `out` always comes first, and I am confident that changing it would wreak havoc.

Is there really a problem with just keeping the `out` in the method signatures? In the original issue above, @stelfrich wrote:

> ```
> (RandomAccessibleInterval out?) =
    net.imagej.ops.image.integral.DefaultIntegralImg(
        RandomAccessibleInterval out?,
        RandomAccessibleInterval in,
        int order?)
> ```
> should have (according to my understanding) a method `method(RandomAccessibleInterval in, int order)` in the namespace.

But that is not true. The signatures should be:

```
integralImg(out, in, order)
integralImg(out, in)
integralImg(in)
```
And that is all. Then the completeness test should not complain.

Is that workable for you?

**Comment by stelfrich** [comment]
> Is that workable for you?

It is. I have worked around it by removing the optional `order` parameter in that specific case.

In general, I am losing the `FunctionOp` part of the `HybridCF` in conjunction with any optional parameter, right @ctrueden?

**Comment by ctrueden** [comment]
> In general, I am losing the FunctionOp part of the HybridCF in conjunction with any optional parameter, right @ctrueden?

Nope, you can just pass `null` for the `out` variable. And it will synthesize a new one function-style.
