### ISSUE TITLE
'No matching op' using HybridCF

### ISSUE THREAD

**Issue by SimonSchmid** [imagej/imagej-ops#390]
I use an AbstractUnaryHybridCF op and have one (not required) parameter. If i call the op with
output = ops.run(MyOp.class, input, parameter), an error occurs because of no matching op.
If i call it with  ops.run(MyOp.class, output, input, parameter), no error occurs? 
Is this a purposed behaviour?

B.t.w, output = ops.run(MyOp.class, input) does not throw an error.

**Comment by ctrueden** [comment]
Yes, you have to pass null (or a `Class` typed null placeholder) for the `out`. The matcher drops optional parameters from right to left. And `out` is optional. While it would be nice for the matcher to try more combinations, it gets hairy fast. And I actually spent multiple days of the January 2014 Konstanz hackathon trying to improve the behavior with respect to `BOTH` parameters like `out`—but our idea did not work out well, so we reverted it.

This is a very Frequently Asked Question at this point, so we should really document it somewhere. [Here](http://imagej.net/ImageJ_Ops#FAQ), I guess.
