### ISSUE TITLE
Wrap iterative flood fill as an op

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-ops#391]
@axtimwalde [writes](https://gitter.im/imagej/imagej-ops/archives/2016/04/25):

> Hey ops developers, @hanslovskyp has just finished an iterative (vs recursive) generic (int terms of type and neighborhood) n-dimensional flood-fill implementation https://github.com/imglib/imglib2-algorithm/tree/master/src/main/java/net/imglib2/algorithm/fill
> we did not feel comfortable including this as an op upfront but if anybody here feels like wrapping it up we would be excited

**Comment by ctrueden** [comment]
@LeonYang5114 Please take a look. I'm guessing it will be easy to integrate this into the morphology namespace.

**Comment by LeonYang5114** [comment]
I think we want to copy and paste the source code and make minimum modification to make it fit into an op, right?

Also there is a few questions: why the value of the target RAI matters? so this operation is inherently in-place? Should we create a `fill` package and namespace?

**Comment by axtimwalde** [comment]
@LeonYang5114 

> why the value of the target RAI matters?

because you need to know where you've been already.

> so this operation is inherently in-place? 

Nope.

**Comment by dietzc** [comment]
Actually, we don't want to copy & Paste the source. rather wrap the original implementation. If this is not possible, we have to understand why and then solve the problem.

**Comment by tibuch** [comment]
Imglib2 implementation is the new DefaultFloodFill.
