### ISSUE TITLE
Heuristics in ThresholdNamespace methods

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-ops#403]
With the current implementations in `ThresholdNamespace` the local thresholding ops that are backed by integral images are not actually used due to the higher priority of their "normal" counterparts (see [ThresholdNamespace.java#L431](https://github.com/imagej/imagej-ops/blob/62256de7e5f9f5a85bb51970735cb16fdfa98d60/src/main/java/net/imagej/ops/threshold/ThresholdNamespace.java#L431)).

In this particular case we cannot decide which implementation to use solely based on the parameters and the matching. What's the opinion on introducing some heuristics in those methods that direct the calls to specific implementations based on properties of the parameters (e.g. if `Shape.getSpan() >= 3` use the integral version).

I feel that this could make life a lot easier when working with the namespace methods from scripts as long as the outputs are guaranteed to be the same for both implementations (I have addressed that issue on the [`local-threshold-oobf-refactoring`](https://github.com/imagej/imagej-ops/tree/local-threshold-oobf-refactoring) branch).

**Comment by dietzc** [comment]
this can already be done using `conforms`. The highest priority `Op` can check if it makes sense to use this `Op`. If not, we will take an `Op` with lower priority which conforms etc ...
the problem with the `Integral` versions of `LocalThresholding` however is, that we get inconsistent results and the `OOB` factory is more or less ignored in the `Integral`case.

**Comment by stelfrich** [comment]
> the problem with the Integral versions of LocalThresholding however is, that we get inconsistent results and the OOB factory is more or less ignored in the Integralcase.

That has been addressed (on [`local-threshold-oobf-refactoring`](https://github.com/imagej/imagej-ops/tree/local-threshold-oobf-refactoring)).

> this can already be done using conforms. The highest priority Op can check if it makes sense to use this Op. If not, we will take an Op with lower priority which conforms etc ...

I will look into this. Thanks @dietzc!
