### ISSUE TITLE
Bug in ConvexHull3D

### ISSUE THREAD

**Issue by kephale** [imagej/imagej-ops#414]
@tibuch, it seems like ConvexHull3D isn't producing a correct hull. The attached figure has the input mesh in red, and hull in green.

![image](https://cloud.githubusercontent.com/assets/400105/16713034/fa4f99f8-469a-11e6-8e40-dd2bfefd45db.png)

**Comment by kephale** [comment]
Additionally, double checking the qhull results via MeshLab with the red mesh shows that a completely enclosing hull does get computed.

**Comment by kephale** [comment]
It is fair to call this one closed. However, I would suggest modifying the ConvexHull docs to indicate that the mesh should be centered at zero (at least that seemed to fix it, but I still can't explain that weird clump of points you found). I added a centerMesh() method to DefaultMesh in the [MeshOps](https://github.com/imagej/imagej-ops/tree/MeshOps) topic branch.

**Comment by tibuch** [comment]
I just did another test with a non-centered point-cloud and the convex hull was correct.

Since ConvexHull is only removing points, I don't think that the mesh has to be centered.
