### ISSUE TITLE
Fix Javadoc rendering of generated Ops interfaces

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-ops#426]
The javadoc for the autogenerated Ops classes is partially broken. For example, the [`Ops.Convert.Bit` javadoc](http://javadoc.imagej.net/ImageJ/net/imagej/ops/Ops.Convert.Bit.html) contains the following (invalid) HTML:

```html
<div class="block">Base interface for "bit" operations.
 <p>
 Implementing classes should be annotated with:
 </p>

 <pre></div>
```
which is an incomplete rendering of the code in the [`Ops.vm` template](https://github.com/imagej/imagej-ops/blob/master/src/main/templates/net/imagej/ops/Ops.vm#L65-L67):

```java
	/**
	 * Base interface for "$op.name" operations.
	 * <p>
	 * Implementing classes should be annotated with:
	 * </p>
	 *
	 * <pre>
	 * @Plugin(type = Ops.${opClass}.class)
	 * </pre>
	*/
```

**Comment by stelfrich** [comment]
The `@Plugin` annotation is parsed as (unknown) Javadoc annotation in that content, @imagejan. That lead to the whole line not being rendered into proper Javadoc.

This error and some additional ones are fixed in #427.
