### ISSUE TITLE
Convenience of namespaces for scripting

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-ops#442]
Take the following Op as an example:

``` java
@Plugin(type = TestParameter.class, priority = Priority.HIGH_PRIORITY)
public class TestParameterOp<T extends RealType<T>> extends AbstractNullaryComputerOp<T> implements TestParameter {

    @Parameter
    T param1;

    public TestParameterOp() {}

    @Override
    public void compute0(T output) {}   
}
```

The completeness test requires the following method:

``` java
@OpMethod(op = TestParameterOp.class)
public <T extends RealType<T>> T test(final T out, final T param1) {
    final T result = (T) ops().run(TestParameterOp.class, out, param1);
    return result;
}
```

To use this method from a script, I'll have to explicitly create new instances of subtypes of `RealType`: `test(out, new DoubleType(1.0))`, while `test(out, 1.0)` seems much more desirable.

I guess it is not possible if we only have type-safe methods in the namespace? Otherwise, `Converters` might be an option?

**Comment by ctrueden** [comment]
That's the two-edged sword of type safety.

We need to have _type-safe_ and _dynamic_ signatures for invoking ops, as well as looking up ops. I have been planning to do that for a long time now, but still never filed an issue for it. I finally did so: #502.
