### ISSUE TITLE
Fitting Ellipse

### ISSUE THREAD

**Issue by tibuch** [imagej/imagej-ops#452]
I would like to verify major- and minor-axis features (geometric 2d) https://github.com/imagej/imagej-ops/issues/449.

My understanding of major- and minor-axis is, that we fit an ellipse to the given shape and take the major- and minor-axis of the ellipse.

Since I am trying to verify the numbers I am looking for implementations in Matlab/python. 

The problem is, that I found a lot of different results. All are more or less similar (+/- 5).

What I found out about the current ops-implementation:
- [Based on ImageJ1 (EllipseFitter -> getEllipseParam()) ](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/geom/geom2d/DefaultMinorMajorAxis.java#L60) which is probably based on [Fitting an ellipse to an arbitrary shape: implications for strain analysis](http://www.sciencedirect.com/science/article/pii/S0191814103000932) 
- Adapted to polygons, based on this [paper](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwixramIq7fPAhWhNpoKHZEoAdYQFggeMAA&url=https%3A%2F%2Fiuks.informatik.tu-muenchen.de%2F_media%2Fmembers%2Fsteger%2Fpublications%2F1996%2Ffgbv-96-05-steger.pdf&usg=AFQjCNEwLW6iznp_ngg_6C9oZE7Mo0MF1g&sig2=XZ1GpM0-6G9GHf79zY12uA)

What I found about minor- and major-axis:
- [Use the minimum bounding box (python).](http://stackoverflow.com/questions/13542855/python-help-to-implement-an-algorithm-to-find-the-minimum-area-rectangle-for-gi)
- [Use a LS estimation to fit an ellipse (Matlab).](https://de.mathworks.com/matlabcentral/fileexchange/3215-fit-ellipse)
- [Use a fast and non-iterative ellipse fit (Matlab).](https://de.mathworks.com/matlabcentral/fileexchange/22684-ellipse-fit--direct-method-)

Questions:
1. Keep our implementation and assume correctness?
2. Replace our implementation?

**Comment by dietzc** [comment]
@haesleinhuepf @bnorthan @ctrueden @stelfrich do you guys have any opinion on this?

**Comment by dietzc** [comment]
If I understand correctly, we currently have the same implementation as IJ1 (just on `Polygon`s not on pixels at the moment) and this one implements the mentioned papers? If our implementation is correct, I'd leave it as is until someone comes up with good reasons why the implementation is not good enough.

**Comment by tibuch** [comment]
I would replace the current polygon-based implementation with an implementation similar to the non-iterative ellipse fit and keep the current implementation only for pixel-based ellipse fitting.

**Comment by tibuch** [comment]
I found this implementation with provided paper: http://research.microsoft.com/en-us/um/people/awf/ellipse/

This looks fast and robust.

**Comment by tibuch** [comment]
I was able to verify the results of minor-major-axis in the 2D geometric featureset. 

> 1. Keep our implementation and assume correctness?

Our implementation is correct.
