### ISSUE TITLE
Move Initializable to Scijava

### ISSUE THREAD

**Issue by lnyng** [imagej/imagej-ops#455]
[`Initializable`](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/Initializable.java) is a very general concept. It makes many sense to move it to upstream project like scijava-common.

One important reason for this is that when using an op as a module (which we should be able to do), the `Initialize` method is not called. Right now, the method is called inside [`DefaultOpMatchingService`](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/DefaultOpMatchingService.java#L425), and the [`InitPreprocessor`](https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/module/process/InitPreprocessor.java) knows nothing about `Initializable`. 

One solution would be making `CommandModule` check if `getDelegateObject()` is `Initializable` inside the [`initialize`](https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/command/CommandModule.java#L148). This could solve the problem for op, but we might also other `Module` implementations to recognize the `Initializable` interface.

@ctrueden Any thoughts?

**Comment by ctrueden** [comment]
Indeed, the idea was always to migrate this interface into SJC later. Feel free to file a PR for that if you wish! Or I will take care of it later.

**Comment by lnyng** [comment]
Would it be better to file PR in both projects? Would the pom dependency be a concern?

**Comment by ctrueden** [comment]
> Would the pom dependency be a concern?

We will just need to bump the parent POM version here in imagej-ops, once scijava/scijava-common#249 is merged and a new scijava-common release has happened. After that, we can delete the `Initializable` class here in Ops, in favor of the SJC one.

**Comment by ctrueden** [comment]
SciJava Common gained the `Initializable` interface in scijava/scijava-common@e5d37f042cc6bc3ae58103a610db2b9aa6abf9b2, available in 2.62.0 and later.

For backwards compatibility reasons, we cannot remove `net.imagej.ops.Initializable` from this incarnation of imagej-ops. But the ImageJ Ops v2 redesign will not have this redundancy.
