### ISSUE TITLE
Frangi Vesselness filter

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-ops#490]
Since @mhl has asked that someone took over his Frangi Vesselness filter implementation ([fiji/Feature_Detection](https://github.com/fiji/Feature_Detection)) we could refactor it to an op.

He has also raised some concern about the correctness in comparison with a [MATLAB implementation](http://de.mathworks.com/matlabcentral/fileexchange/24409-hessian-based-frangi-vesselness-filter) (see http://imagej.net/Frangi) that would need to be tackled.

**Comment by stelfrich** [comment]
@tinevez is working on a `TubenessOp` at https://github.com/tinevez/imagej-ops/commit/84ebb7d1538356d809846facee2d6ec5ca35d4b8. The `FrangiVesselnessOp` and the `TubenessOp` should share most of their boilerplate code...

**Comment by danielsnider** [comment]
+1

**Comment by imagejan** [comment]
See also [this discussion](http://forum.imagej.net/t/frangi-vesselness-filter-feedback/6747?u=imagejan) on the forum.

**Comment by stelfrich** [comment]
Fixed by https://github.com/imagej/imagej-ops/commit/edd451315debec105fa0b121e6d40bd4defc2a1 (merging #525).
