### ISSUE TITLE
Discard optional "both" parameters preferentially to "input" parameters

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#50]
We want the `out` parameter of `OutputFunction` implementations to be discarded preferentially to later optional inputs, if any. We can accomplish this in a general way by preferring optional "both" parameters (also from right to left) to pure "input" parameters, when deciding the order of optional inputs to discard.

The alternative would be to check against every possible combination of missing optional parameters, but that is exponential (e.g., twenty missing optional inputs would be 2^20 > 1 million combinations already...). So let's stick to right-to-left, but do "both" parameters first followed by "input" parameters.

**Comment by ctrueden** [comment]
Fixed in 84c680057a6344bf66342807b2181abe32e7f51e. Tested in 91349a409288cc561d655ba2037f532e9c549f3f.

**Comment by ctrueden** [comment]
Note that this change was reverted in 9335808ae2b3328341e371708b13f67577de7407, for reasons outlined in that commit message.
