### ISSUE TITLE
Add ConcatenateView op

### ISSUE THREAD

**Issue by hanslovsky** [imagej/imagej-ops#500]
I implemented a `ConcatenateView` op that allows to concatenate a list of `RandomAccessibleInterval` along the specified dimension, following what is in `imglib2` `Views`:
https://github.com/imagej/imagej-ops/compare/imagej:eada2b8...hanslovsky:b4df842

The pull request will have to wait until `imglib2-4.1.0` is released. I created this issue to ensure I won't forget about it and so others know the code exists and avoid code duplication.

**Comment by ctrueden** [comment]
@hanslovsky If you don't mind, I'll have @gselzer take care of filing this as a PR.

**Comment by hanslovsky** [comment]
@ctrueden @gselzer I do not mind so feel free to go ahead.

**Comment by ctrueden** [comment]
Resolved with the merge of #518.
