### ISSUE TITLE
Need to detect NAN on paired number

### ISSUE THREAD

**Issue by ilan** [imagej/imagej-ops#522]
All is OK in 2D but in 3D, there is a missing check on pixels[sz][sy][sx] != Integer.MAX_VALUE.
I have added it below:

	for (int z = 0; z < pixels.length; z++) {
		for (int y = 0; y < pixels[z].length; y++) {
			for (int x = 0; x < pixels[z][y].length; x++) {

				// ignore pixels not in mask
				if (pixels[z][y][x] == Integer.MAX_VALUE) {
					continue;
				}

				// get second pixel
				final int sx = (int) (x + orientationAtX);
				final int sy = (int) (y + orientationAtY);
				final int sz = (int) (z + orientationAtZ);

				// second pixel in interval and mask
				if (sx >= 0 && sy >= 0 && sz >= 0 && sz < pixels.length
						&& sy < pixels[sz].length
						&& sx < pixels[sz][sy].length
						&& pixels[sz][sy][sx] != Integer.MAX_VALUE) {

					matrix[pixels[z][y][x]][pixels[sz][sy][sx]]++;
					nrPairs++;
				}
			}
		}
	}

**Comment by salimkanoun** [comment]
Just to precise it is about CooccurrenceMatrix3D.java
http://forum.imagej.net/t/looks-like-a-bug-in-cooccurencematrix3d/6832

**Comment by ctrueden** [comment]
Thanks @ilan and @salimkanoun, I committed your fix as ae691c5f38542cf3e94b88f33a1ad235b754777c!

Please feel welcome to file a PR next time, so that you get direct credit in the git history.
