### ISSUE TITLE
Gibson Lanni Diffraction Kernel Discrepancies

### ISSUE THREAD

**Issue by eric-czech** [imagej/imagej-ops#550]
I noticed that results from the ```DefaultCreateKernelGibsonLanni``` class seem to disagree with some other implementations of the same algorithm.  I could very well be missing something and I'm hoping this is good enough context (for @bnorthan and @hijizhou I think), but here's what I found:

I'm using inputs like this to the imagej-ops implementation:

```
Img<DoubleType> img = ops.create().kernelDiffraction(
	new FinalDimensions(64, 64, 9),
	.75, // NA 
	670E-09, // lambda 
	1.33, // Specimen RI 
	1.5,  // Immersion RI 
	377E-9, // Res Lateral 
	1500E-9, // Res Axial
	2000E-9, // Particle Position 
	new DoubleType()
);
```

To attempt to do the same thing with a different implementation I tried the [python version](http://kmdouglass.github.io/posts/implementing-a-fast-gibson-lanni-psf-solver-in-python.html) (after wrapping all that up in a function) with arguments like this:

```
img = psf.GibsonLanni(
    size_x=64, size_y=64, size_z=9,
    na=.75,
    ni0=1.5, ni=1.5, # Immersion RI
    ng0=1.5, ng=1.5, # Coverslip RI
    ns=1.33,         # Specimen RI

    # All of the following are in microns
    wavelength=.67,  # aka lambda
    res_lateral=.377,
    res_axial=1.5,
    pz=2.
)
```

I also then compared this to [PSFGenerator] using the Gibson & Lanni model with those same arguments above.  Both PSFGenerator and the Python version produced essentially identical results that looked something like this (across all 9 XY planes):

![psf-py](https://user-images.githubusercontent.com/6130352/38323162-75b8ca3a-380a-11e8-98b7-b4f8c1f1f790.gif)

While the imagej-ops version produced something like this instead:

![psf-java](https://user-images.githubusercontent.com/6130352/38323200-94e9006e-380a-11e8-8138-3abc6e4163ec.gif)

I actually tried a bunch of other combinations of parameter settings too and never found a case where the Python and PSFGenerator versions differed by much, yet I can't seem to get the imagej-ops results to be comparable.

One thing I noticed was that the **lambda_0** parameter mentioned in the [paper](http://www.ee.cuhk.edu.hk/~tblu/monsite/pdfs/li1702.pdf) seems to be 436nm but in the imagej-ops version (as well as the original Matlab) it's 545nm.  Hopefully I'm interpreting that correctly but either way I tried forcing 436nm as the setting in ```DefaultCreateKernelGibsonLanni``` as well as setting it to 545nm in the python version but it made no difference.

Do you guys have any idea what might be different about the java version here?  I assume PSFGenerator is a good ground-source of truth so I thought it worth mentioning this once I saw the java version deviating so much from it.

**Comment by bnorthan** [comment]
Hi @eric-czech 

Thanks a lot for testing.  I just looked at this, and it seems if I use the 0.40.0 SNAPSHOT version of imagej ops, I get a better result.   If you have a chance can you let me know if the incorrect result still happens when you use the latest SNAPSHOT??   If you need instructions as to how to build the snapshot, or you want me to send you a copy let me know (I'm not sure if your actively developing maven projects, if not it might be a bit of a pain to set things up).   It's possible this [commit](https://github.com/imagej/imagej-ops/commits/47977a34160b534f526769be4eec72d85957f748/src/main/java/net/imagej/ops/create/kernelDiffraction/DefaultCreateKernelGibsonLanni.java) fixed the issue.  

To use the latest snapshot you probably have to clone [imagej-ops](https://github.com/imagej/imagej-ops), and build (just typing 'mvn' at the command line is good enough) 

<dependency>
	<groupId>net.imagej</groupId>
	<artifactId>imagej-ops</artifactId>
	<version>0.40.0-SNAPSHOT</version>
</dependency>

**Comment by ctrueden** [comment]
Thanks for the quick reply, @bnorthan. I second the idea of testing with the latest imagej-ops snapshot.

Regarding how to obtain said snapshot: thanks to Travis CI, it is already built and available from the Maven repository. Download it [here](http://maven.imagej.net/service/local/artifact/maven/redirect?r=snapshots&g=net.imagej&a=imagej-ops&v=LATEST&e=jar).

Or if you are using it from another Maven project that extends the pom-scijava parent, you can simply write the following into your `pom.xml`:
```
<properties>
  <imagej-ops.version>0.40.0-SNAPSHOT</imagej-ops.version>
  <enforcer.skip>true</enforcer.skip>
</properties>
```

**Comment by eric-czech** [comment]
Thanks guys!  I’m traveling at the moment but will give that a shot as soon as I get back this weekend.

**Comment by eric-czech** [comment]
Hey guys, I tried another comparison using the latest snapshot build and the results look better but they still seem pretty off overall if I'm doing this correctly.  For example, I took the same arguments currently being used in the [unit test](https://github.com/imagej/imagej-ops/blob/master/src/test/java/net/imagej/ops/create/kernelDiffraction/CreateKernelDiffractionTest.java) for a 10x10 2D kernel and tried a small 16x16x8 3D kernel from PSFGenerator, the python version, and both java versions (pre and post upgrade to the latest snapshot) and was seeing something like this on just the first z-slice (but this is pretty representative of the differences between all of them):

<img width="1273" alt="screen shot 2018-04-07 at 6 07 03 pm" src="https://user-images.githubusercontent.com/6130352/38460785-09b28466-3a8f-11e8-9cf0-8e3a6726ab46.png">

At least for the java versions, I was generating the kernel like this:

```java
		Img<FloatType> img = ops.create().kernelDiffraction(
			new FinalDimensions(16, 16, 8), 
			1.4, // NA 
			610E-09, // lambda 
			1.33, // Specimen RI 
			1.5,  // Immersion RI 
			100E-9, // Res Lateral 
			250E-9, // Res Axial
			2000E-9D, // Particle Position 
			new FloatType()
		);
```
The differences there between the pre and post update versions are less pronounced than between the original arguments I was trying, which you can see in the same kind of comparison here:

<img width="1263" alt="screen shot 2018-04-07 at 6 09 55 pm" src="https://user-images.githubusercontent.com/6130352/38460787-0f462e28-3a8f-11e8-8452-20cc056b5bd6.png">

And in this case, the java-based kernels were created like this:

```java
		Img<FloatType> img = ops.create().kernelDiffraction(
			new FinalDimensions(16, 16, 8), 
			.75, // NA 
			670E-09, // lambda 
			1.33, // Specimen RI 
			1.5,  // Immersion RI 
			377E-9, // Res Lateral 
			1500E-9, // Res Axial
			2000E-9D, // Particle Position 
			new FloatType()
		);
```

Either way, the updates certainly made a difference but given that the difference between PSFGenerator and Python is virtually nothing by comparison (at least visually) I have to imagine there's still a pretty significant difference somewhere.  It could be in some of the other arguments not shown above, but I went through and carefully tried to match them so hopefully that's not it.

Let me know if you guys have any ideas, but I had a few questions in the meantime:

1. Are 3D kernels an intended use case?  I just assumed it was but it seems like a good time to double check
2. I'd like to eventually submit a PR with additional test cases that included comparisons of results to tif files stored much like the resources used in other tests (from PSFGenerator for ~20KB stacks) with error tolerances tuned to expect differences like those between Python vs PSFGenerator so let me know if you think there's a better way to approach testing it, or if there's just some other way you see to make this kind of a comparison repeatable.

Thanks again for the help!

**Comment by hijizhou** [comment]
Hi all,  I have again a quick test of [the java version](https://github.com/hijizhou/MicroscPSF-ImageJ). It can produce almost the same image as left two images. I am starting to look at the Ops version.

One thing I notice is that Ops re-cropped a centered psf after computation. Probably it is the reason why they are different? I am not sure at this moment. I will test the Ops version after my flight landing. It is going to take off now ;-)

**Comment by bnorthan** [comment]
Hi @hijizhou 

You bring up a good question.  If either you or @eric-czech are able to share images I recommend you start a discussion about conditioning the theoretical PSF for deconvolution on the [forum](http://forum.imagej.net/).  This is a complicated issue and there are many factors to consider.

1.  Should you center the PSF?
2.  How large does the PSF need to be??  (even using the same imaging parameters, the deconvolution result will be different between different PSF sizes)
3.  How do you estimate parameters such as refractive index of the sample and particle depth, for a real image  where both can be varying throughout the sample??  (ie the sample is obviously located at different positions, and the refractive index of the sample may be varying).

**Comment by eric-czech** [comment]
Ah ok, that definitely seems to be it (i.e. centering differences).

Here is a view nearly orthogonal to the z-axis for a PSF using those same arguments you used above but with **particle position = 0** for PSFGen, Python, IJOps post-update and IJOps pre-update and they're all visually the same except for the older IJOps version (which I'll stop including from here on):

<img width="1110" alt="screen shot 2018-04-08 at 12 05 51 pm" src="https://user-images.githubusercontent.com/6130352/38469686-e89eea2e-3b26-11e8-9717-dfc877d2fd22.png">

With particle position 2um in the same view, the results are obviously different like you mentioned they'd be so that certainly seems to account for the differences I was talking about before:

<img width="839" alt="screen shot 2018-04-08 at 12 00 24 pm" src="https://user-images.githubusercontent.com/6130352/38469717-5acf62cc-3b27-11e8-9eee-d1d492f304f4.png">

And for the sake of posterity, another set of arguments with a much lower wavelength (425nm) is now the same for all implementations too with pZ=0:

<img width="908" alt="screen shot 2018-04-08 at 12 13 36 pm" src="https://user-images.githubusercontent.com/6130352/38469720-61cfb63a-3b27-11e8-93ce-975b9dbc61ae.png">

In general it was my understanding that a non-centered PSF wouldn't make any sense for use in deconvolution and I had no idea the GL model from PSF generator was doing that until you pointed it out (never had to worry about it w/ the Richards|Born & Wolf models I had been using before).

@hijizhou did you have any initial reasons for going with the un-centered PSF?  I thought that centering was a pretty core assumption of the diffraction models but it wouldn't surprise me in the least to find out that's wrong or an oversimplification on my part.  

I'll close this out and move the discussion to the forum from here on if you guys don't have any additional thoughts/concerns that might be more implementation-oriented.

**Comment by ctrueden** [comment]
I want to thank you all (@eric-czech @bnorthan @hijizhou) for your thoroughness and responsiveness. I always love it when issues get resolved quickly! :+1:

**Comment by hijizhou** [comment]
Thanks to all guys. 
@eric-czech, I didn't consider too much about this PSF centering. I think if the PSF space is infinite (shifting doesn't loss information), both cases should be identical since shifting doesn't bring any distortions for the convolution model. Of course, we need to differentiate them in real situations. 
@bnorthan, I will move to the forum for further discussion. Certainly, PSF varies throughout samples. That's why there are many works on depth-variant (or even asymmetric in x-y space) image deconvolution for thick samples. My personal opinion (at least this moment), however, is that current convolution model with one PSF has already been a good approximation for most real cases.

By the way, this issue brings me to think how to keep consistency among different implementations of the same algorithm (in an easy way). I mean for example, in a single java program, we can call different programming languages (Matlab, Python, jar etc) to compare results. Do you guys have ideas to approach it? Thanks.

**Comment by eric-czech** [comment]
Sure thing @ctrueden -- loving this project by the way, great job you have all done with these implementations!

Oh ok I think I'm following @hijizhou.  I visualize what you said as a PSF with identical shape and structure simply shifted somewhere along the z-dimension (or any other for that matter) but with enough room in the resulting volume that no parts of it get cut off -- is that what you mean that it wouldn't distort the convolution model?  To me it seems like that would mean that a deconvolution result would be translated but still have the same shape within the volume, which makes sense.

I think the last thing I'm stuck on then is simply:  Is the ops implementation with its automatic cropping and centering the only sort of "safer" way (haven't seen any other implementations do that yet) to generate Gibson-Lanni kernels without potentially generating volumes that get cropped off or distorted in a way that users don't realize would fairly drastically effect deconvolution results?  That's the sort of interpretation I'll walk away with but let me know if that's not a complete picture.

**Comment by eric-czech** [comment]
I started a related forum thread (http://forum.imagej.net/t/diffraction-kernel-i-e-psf-generation-pitfalls/10349) by the way so I'll close this out to start tracking any more conversation there instead.

**Comment by hijizhou** [comment]
Thanks a lot, Brian. I am very interested in that kind of tests. However, I am pretty busy these days... Please discuss first and I will join you shortly.
