### ISSUE TITLE
watershed crashes when seeds are at edge of mask

### ISSUE THREAD

**Issue by tischi** [imagej/imagej-ops#579]
@imagejan 
please see here: https://forum.image.sc/t/watershed-ops-strange-behaviour/20189

**Comment by ctrueden** [comment]
Thanks for the report, @tischi.

@SimonSchmid Any chance you have time and interest to investigate, since you coded this op?

**Comment by SimonSchmid** [comment]
Hi,
Interest, yes. But I will be very busy for at least the next 6 months and won't find any time I think. Sorry!

**Comment by ctrueden** [comment]
@SimonSchmid Totally understandable. Thanks for responding.

**Comment by frauzufall** [comment]
Hey, I made a [PR](https://github.com/imagej/imagej-ops/pull/615) to fix this, if anyone has time to review it, that'd be great :)

**Comment by ctrueden** [comment]
Fixed by #615.
