### ISSUE TITLE
distancetransform uses wrong order for in and out

### ISSUE THREAD

**Issue by dariomel** [imagej/imagej-ops#590]
in the following code, which comes from `ImageNamespace.class`, the arguments `in` and `out` are swapped in the signature of `distancetransform`, as the convention seems to be that `out` comes before `in`. More seriously, the arguments are also swapped in the call to `ops().run()`, which **expects** the opposite order (first `out` then `in`), as specified by the `CommandInfo` associated with the `Op` in question.

```java
	/** Executes the "distancetransform" operation on the given arguments. */
	@OpMethod(ops = {
		net.imagej.ops.image.distancetransform.DefaultDistanceTransform.class,
		net.imagej.ops.image.distancetransform.DistanceTransform2D.class,
		net.imagej.ops.image.distancetransform.DistanceTransform3D.class })
	public <B extends BooleanType<B>, T extends RealType<T>>
		RandomAccessibleInterval<T> distancetransform(
			final RandomAccessibleInterval<B> in,
			final RandomAccessibleInterval<T> out)
	{
		@SuppressWarnings("unchecked")
		final RandomAccessibleInterval<T> result =
			(RandomAccessibleInterval<T>) ops().run(Ops.Image.DistanceTransform.class,
				in, out);
		return result;
	}
```

**Comment by ctrueden** [comment]
Thanks for catching this and reporting, @dariomel!

@gselzer Can you please fix?
