### ISSUE TITLE
Add morphological ops

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-ops#62]
This includes `dilate`, `erode`, `open` and `close`.

And we want them to work on arbitrary structuring elements.

**Comment by ctrueden** [comment]
I just browsed the Imglib2 Morphological Operations wiki page, and holy cow has a lot of work gone into this over the past two years. And it's still not merged to master anywhere? What are the obstacles there? Is there anything a student at LOCI or Uni Konstanz could do to help?

**Comment by dietzc** [comment]
@tibuch will work on this after he finishes the view stuff. Should be ready end of August.

**Comment by ctrueden** [comment]
@landinig wrote:
> you could consider that the border of the image is the end of the universe (and it gets eroded, as outside it is 0), or you can asume that this is a window in a much larger universe (and so you assume it is filled) and remains not eroded. Some might not worry too much about this detail, but there are good reasons for dealing with those distinct 2 cases, it would break a large amount of our code if that is changed.

Just wanted to comment that both of those cases are fully covered in ImgLib2 by the use of "out of bounds strategies". So I think there is no problem here.

**Comment by ctrueden** [comment]
Addressed in #358.
