### ISSUE TITLE
Quesrtion: Sobel filter

### ISSUE THREAD

**Issue by ctr26** [imagej/imagej-ops#626]
This is a crosspost at the[ imagej forum:](https://forum.image.sc/t/slice-wise-sobel-using-ops/)

How would run a (2D) sobel filter through a 3D volume slice wise using imagej ops?

The following code works for a DOG slice wise filter (I think, borrowed from an example) ,but switching in the sobel filter causes an error. I’m pretty sure using ops.filter().sobel(img) produces an n-dimensional sobel filter?
```

#@ Dataset data
#@OUTPUT Dataset output
#@ OpService ops
#@ DatasetService ds

from net.imagej.axis import Axes
converted = ops.convert().float32(data.getImgPlus())

dog = ops.create().img(converted)

converted_in = ops.transform().flatIterableView(converted)
converted_out = ops.transform().flatIterableView(dog)

dog_op = ops.op("filter.dog", converted_in,1,1)
#dog_op = ops.op("filter.sobel", converted_in)

t_dim = data.dimensionIndex(Axes.TIME)
fixed_axis = [d for d in range(0, data.numDimensions()) if d != t_dim]

ops.slice(converted_out,converted_in, dog_op, fixed_axis)

output = ds.create(converted_out)
```

**Comment by imagejan** [comment]
You asked the [same question](https://forum.image.sc/t/slice-wise-sobel-using-ops/38720?u=imagejan) on the forum. Please always disclose when cross-posting, to avoid that people waste their time in replying with redundant information, and to enable others having a similar issue to follow the discussion.

As this is mostly a usage question rather than an issue with `imagej-ops`, let's continue the discussion on the forum.

**Comment by ctr26** [comment]
> You asked the [same question](https://forum.image.sc/t/slice-wise-sobel-using-ops/38720?u=imagejan) on the forum. Please always disclose when cross-posting, to avoid that people waste their time in replying with redundant information, and to enable others having a similar issue to follow the discussion.
> 
> As this is mostly a usage question rather than an issue with `imagej-ops`, let's continue the discussion on the forum.

Apologies, I've updated my post

**Comment by gselzer** [comment]
Check out #627 for relevant conversation
