### ISSUE TITLE
AbstractPadAndFFTFilter overrides OutOfBoundsFactory parameter of PadAndConvolveFFTF

### ISSUE THREAD

**Issue by Xanthorapedia** [imagej/imagej-ops#628]
When `ops.filter().convolve()` is called with arguments `RAI, RAI, OutOfBoundsFactory`, the result seems as if the input was padded by `OutOfBoundsConstantValueFactory` with value 0 instead of as specified by the last argument.

Example:
```java
import net.imagej.ImageJ;
import net.imagej.ops.OpService;
import net.imglib2.img.Img;
import net.imglib2.img.array.ArrayImgs;
import net.imglib2.outofbounds.OutOfBoundsPeriodicFactory;
import net.imglib2.type.numeric.real.FloatType;

public class WrongPadding {
	public static void main(String[] args) {
		ImageJ ij = new ImageJ();

		OpService ops = ij.op();

		Img<FloatType> ramp = ArrayImgs.floats(256, 256);
		Img<FloatType> average = ArrayImgs.floats(64, 64);

		int i = 0;
		for (FloatType iv : ramp)
			iv.set(i / 256 + (i++) % 256);
		for (FloatType kv : average)
			kv.set(1f / (64 * 64));

		ij.ui().show("Input", ramp);
		ij.ui().show("Zero padding", ops.filter().convolve(ramp, average));
		ij.ui().show("Periodic pading", ops.filter().convolve(ramp, average, new OutOfBoundsPeriodicFactory<>()));
	}
}

```
Results:
![wrong padding](https://user-images.githubusercontent.com/25558041/84620460-ab952c00-ae9d-11ea-8590-c8de1b5c6f03.png)
Both outputs look the same, although I expect the later to at least have some white "bleed-through" at the top and left edges.

It seems the input is first padded by the matched Op [`PadAndConvolveFFTF` with the specified `OutOfBoundsFactory`](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/filter/convolve/PadAndConvolveFFTF.java#L129) but later padded again by [`AbstractPadAndFFTFilter` with zeros](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/filter/AbstractPadAndFFTFilter.java#L215). The first padding keeps the image dimensions the same while the second extends the boundary by 1/2 kernel size, which catches all out-of-bound access to the input image when computing FFT.

**Comment by gselzer** [comment]
Hi @Xanthorapedia!

Thanks for pointing this out. I started work on a fix on the `pass-oobf` branch, if you would like to take a look

**Comment by bnorthan** [comment]
I also made the same change (it was a simple change) https://github.com/imagej/imagej-ops/commit/a8fe660341993196253af5ba20156422974cc467

I added a test as well if it is useful...  feel free to erase my branch.  As I mentioned it was a very trivial change.

**Comment by gselzer** [comment]
Awesome @bnorthan! Great minds think alike!

I might just add my comment to your commit for posterity and then delete my branch, if that is alright with you.

**Comment by bnorthan** [comment]
No problem.

**Comment by Xanthorapedia** [comment]
Thanks guys for your super-fast response! One last thing I found a little annoying is [this debug message print out](https://github.com/imagej/imagej-ops/blob/b7c48d01447ec26502a784b46b7ccb65bc246b90/src/main/java/net/imagej/ops/filter/convolve/ConvolveFFTC.java#L75). Consider turning it into a log or removing it?

**Comment by gselzer** [comment]
@Xanthorapedia see #630

**Comment by Xanthorapedia** [comment]
@gselzer Awesome. Thanks!
