### ISSUE TITLE
Add descriptors/features framework

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-ops#67]
This includes Haralick, Zernike, FirstOrderStatistics, Moments, Shape...

Current work can be seen on the increasingly ill-named [feature-service branch](https://github.com/imagej/imagej-ops/compare/feature-service).

**Comment by dietzc** [comment]
we may not forget to offer ops which respect the calibration of the image. In 2D these are especially the geometric features (area for example). In 3D, these are geometric and also (potentially) intensity based features. The calibration of an image can be passed as double[] array. Basically there are two ways to integrate respect calibration in a feature: 
* we always provide a calibration as an optional input with default values `1.0`. 
* we offer two different implementations of the feature, one with calibration one without.

**Comment by dietzc** [comment]
TODO after reviewing with @ctrueden 

* Renaming Def to Default
* get rid of <? extends RealType<?>> and RealType<?> completely. Introduce generic types if needed.
* Feature<T>?
** Can have some helper methods
* DefaultFeatureService make inner classes private!
* Do I really have to restrict myself on features or can have a "OpCompileService"?!
* OpInfo should be in net.imagej.ops (issue #57). OpArgs ().

**Comment by dietzc** [comment]
see https://github.com/imagej/imagej-ops/tree/outputop-service

**Comment by ctrueden** [comment]
@angrauma A little bird told me that Zernike 3D is also working! Anything else that can be checked off the list above?

**Comment by dietzc** [comment]
@ctrueden haralick 3D, zernike 3D not yet :-)

**Comment by ctrueden** [comment]
@dietzc Oh yeah, right! And it is checked, so I am happy.

**Comment by LeeKamentsky** [comment]
3D zernike? How are you planning to generalize to multiple dimensions? I found this paper here:
http://cg.cs.uni-bonn.de/aigaion2root/attachments/novotni-2003-3d.pdf
which creates a 3D Zernike-like basis set on top of spherical harmonics (think of electron orbitals if you want to get an idea).
So inquiring minds want to know *exactly* what you guys might have planned.

**Comment by angrauma** [comment]
@LeeKamentsky Yes, this is exactly the paper I would like to be oriented towards when implementing 3D Zernike moments. I also want to take a closer look at this paper: http://www.emis.de/journals/HOA/MPE/Volume2012/353406.pdf. 
But it seems the idea is very close to the other paper. So it is the plan to realize the 3D Zernike descriptor as an extension of spherical harmonics based descriptors, as it is explained in the paper of Novotni and Klein, but I have not started yet implementing it, so I can not say how I will do it exactly, at the moment.

**Comment by dietzc** [comment]
another thing we might to work on in the future are quality metrics for images:

e.g. see: http://rsb.info.nih.gov/ij/plugins/mssim-index.html

**Comment by maierl** [comment]
I would _love_ to see the 3D features! all my data will be in 3D, but my analysis is mostly yet limited to 2D.

**Comment by dietzc** [comment]
@angrauma (local binary patterns, tamura, 2D Shape etc) / @tibuch (3D geometry, shape etc.)  please add the remaining / missing features until September.

**Comment by ctrueden** [comment]
Status update on this issue?

**Comment by dietzc** [comment]
I'm implementing the `CachedOpEnviroment` and `FeatureSet` these days. The existing implementations of features can then be used. I will clean-up all the branches and open PRs over the next 24h. I will update the issue then.

**Comment by ctrueden** [comment]
@dietzc Great, thanks!

**Comment by dietzc** [comment]
... approaching ;-) I will close this issue in favour of issues for the missing feature implementations.

**Comment by dietzc** [comment]
closed in favour of several other issues I just created.
