### ISSUE TITLE
Handle Dataset parameters gracefully

### ISSUE THREAD

**Issue by dscho** [imagej/imagej-ops#8]
We have a couple of ops working on `Img` instances, but not on `Dataset` nor on `ImgPlus` ones.

**Comment by ctrueden** [comment]
This issue will be largely addressed by https://github.com/imagej/imagej-common/issues/46.

**Comment by ctrueden** [comment]
Closing, since it will be taken care of by the data model refactor of https://github.com/imagej/imagej-common/issues/46.
