### ISSUE TITLE
Build fails with EnforceByteCodeVersion error

### ISSUE THREAD

**Issue by 9037568** [imagej/imagej-ops#84]
When attempting to build from a fresh clone, the build fails with this error:

Downloaded: http://maven.imagej.net/content/groups/public/org/scijava/junit-benchmarks/0.7.3-scijava/junit-benchmarks-0.7.3-scijava.jar (74 KB at 252.6 KB/sec)
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-rules) @ imagej-ops ---
[INFO] Adding ignorable dependency: null:jcodings:null
[INFO]   Adding ignore: org/jcodings/*
[INFO] Adding ignorable dependency: null:jnr-constants:null
[INFO]   Adding ignore: com/kenai/constantine/*
[INFO]   Adding ignore: jnr/constants/*
[INFO] Adding ignorable dependency: null:jnr-ffi:null
[INFO]   Adding ignore: jnr/ffi/*
[INFO] Restricted to JDK 1.6 yet com.sun:tools:jar:1.4.2:system contains sun/tools/asm/ArrayData.class targeted to JDK 1.7
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
Found Banned Dependency: com.sun:tools:jar:1.4.2
Use 'mvn dependency:tree' to locate the source of the banned dependencies.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.068 s
[INFO] Finished at: 2014-11-23T12:00:49-05:00
[INFO] Final Memory: 30M/185M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-rules) on project imagej-ops: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]

**Comment by ctrueden** [comment]
Resolved as of 486529407ac2f100c10195a941064cbf306005a5.
