### ISSUE TITLE
Move deprecated packages into folder: deprecated

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#91]
Would it be possible to move all deprecated packages (net.imglib2, net.imagej.* which is not ops) into a dedicated folder? There are several reasons why this would make sense from my point of view

* Developers are somehow puzzled where the actual ops development takes place (even if marked as deprecated in the file itself).
* Some packages have the same name as packages in other bundles (OSGi doesn't like this).

I suggest to move them to the base package "deprecated", but I'm not sure what the consequences for other, depending projects might be?!

**Comment by ctrueden** [comment]
Let's discuss at the hackathon. I want to address your requirements (make OSGi happy), but am tentatively against shuffling things around any further. We will be deleting `net.imglib2.meta` out of `imagej-common` in a future release though, which could help you and might alleviate some of the confusion.

**Comment by ctrueden** [comment]
I guess this issue is about `net.imglib2.ops` eh... hmm...

**Comment by dietzc** [comment]
yep. its about ops :-) but however: you are right, lets discuss that next week. I can explain to you where the problems are. for now, I can solve these issues with some tricks.

**Comment by ctrueden** [comment]
Unfortunately, we need to keep `net.imglib2.ops` around until ImageJ2 can fully ditch it in favor of the ImageJ OPS API. It was a dubious decision to merge the classes into `imagej-ops` and get rid of `imglib2-ops`, but what's done is done. Splitting it again would be disruptive and create additional confusion in the form of another (deprecated) JAR file. So, we'll have to live with the KNIP's OSGi workaround until we can get rid of the deprecated classes.
