### ISSUE TITLE
Use a heuristic for default behavior of createimg

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-ops#96]
When calling createimg, whether to use an array, planar or paged cell image container should depend on the size of the dimensions. It could also be specified as a hint. Let's steal the [logic from SCIFIO](https://github.com/scifio/scifio/blob/scifio-0.17.2/src/main/java/io/scif/img/DefaultImgFactoryHeuristic.java#L46-L64).

**Comment by ctrueden** [comment]
Other classes that implement `createOutput` may have the same issue; e.g.: the [AbstractFFTFilterImg](https://github.com/imagej/imagej-ops/blob/91349a409288cc561d655ba2037f532e9c549f3f/src/main/java/net/imagej/ops/fft/filter/AbstractFFTFilterImg.java#L138-L142).

**Comment by ctrueden** [comment]
The SCIFIO logic, because it depends on the amount of available RAM, is not deterministic. So we should probably depend on static cutoffs for the heuristic instead.

**Comment by dietzc** [comment]
it's not only about create images but also about creating new empty containers from `RandomAccessibleInterval`s (e.g. Views). We should also keep in mind to have helper/utilities for `Labeling`s

**Comment by dietzc** [comment]
I'm working on tests for `CreateImg` at the moment which will serve as the basis for further CreateImg methods or some additional `Converters` [1]. However, I'm facing a problem which confuses me a bit:

In the test https://github.com/imagej/imagej-ops/blob/img-creators/src/test/java/net/imagej/ops/create/CreateImgTest.java (WIP) I receive an `IllegalArgumentException` in some logic inside the `DefaultOpMatcher`. I can't figure out why this happens, maybe @ctrueden or @hinerm you have an idea?

[1] https://github.com/imagej/imagej-ops/tree/img-creators

**Comment by ctrueden** [comment]
@dietzc: It's due to an issue with how the `DefaultConverter` handles arrays and collections right now.

Debugging into your test, I see that the `ConvertService` returns `true` for `canConvert(Object arg, Type type)` when `arg` is a `net.imglib2.view.IntervalView` and `type` is a `double[]`, because `DefaultConverter#canConvert` returns `true`, because `dest` (the `type`) [is an array](https://github.com/scijava/scijava-common/blob/scijava-common-2.38.2/src/main/java/org/scijava/convert/DefaultConverter.java#L291-L292).

I would call this a bug. We should have a separate, dedicated, very-low-priority converter implementation for arrays, as I mentioned [here](https://github.com/scijava/scijava-common/issues/109#issuecomment-78510451).

**Comment by dietzc** [comment]
Until this converter is in place, I should be able to write a high-priority converter for `IntervalView` or `RandomAccessibleInterval` which will be used prior to the `DefaultConverter`?

**Comment by ctrueden** [comment]
@dietzc Definitely.

**Comment by dietzc** [comment]
@DanielSeebacher will work on this. Working packages are as follows

1. Converters (see also discussion above): https://github.com/imagej/imagej-ops/issues/54
2. Implement functionality to create images / RAIs from: Other RandomAccessibleIntervals, Images, RandomAccessible + Interval, Interval + Factory + Type etc. All kind of combination which are currently missing
3. Implement functionality to create Labelings (the new one of Tobias)

@tibuch will support him!

**Comment by dietzc** [comment]
can be closed. see: https://github.com/imagej/imagej-ops/pull/123.
